---
version: "3.6"

services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-mysql:ubuntu-5.2.*
    restart: always
    container_name: zabbix-proxy
    ports:
      - 0.0.0.0:${ZABBIX_PROXY_PORT:-10051}:10051
    environment:
      - ZBX_PROXYMODE=${ZBX_PROXYMODE:-0}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME:-zabbix-proxy}
      - ZBX_SERVER_HOST
      - ZBX_SERVER_PORT=${ZBX_SERVER_PORT:-10051}
      - ZBX_ACTIVESERVERS
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=${DB_SERVER_PORT:-3306}
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbixMonitorSV2021
      - MYSQL_ROOT_PASSWORD=zabbixMonitorSV2021Mediast3p

    volumes:
      - ./enc:/var/lib/zabbix/enc:ro
    stop_grace_period: 1m
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:8.0.23
    container_name: mysql-server
    restart: always
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
     - mysql-vol:/var/lib/mysql
     #- c1d253c99cfd2acf7898b3c6735f5175c76a816da1711496a0b530c894e6f70a:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixMonitorSV2021
      MYSQL_ROOT_PASSWORD: zabbixMonitorSV2021Mediast3p
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
